services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile

    image: tickweave-backend:0.1.0

    restart: unless-stopped

    expose:
      - "8080"

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile

    image: tickweave-frontend:0.1.0

    restart: unless-stopped

    ports:
      - "8081:80"

    depends_on:
      backend:
        condition: service_healthy