services:
  backend:
    image: ghcr.io/justaksi7/tickweave-backend:0.1.0

    restart: unless-stopped

    expose:
      - "8080"

  frontend:
    image: ghcr.io/justaksi7/tickweave-frontend:0.1.0

    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      backend:
        condition: service_healthy